export const randomNames = [
  "Gretchen",
  "Renata Sorrah",
  "Nazaré Tedesco",
  "Gloria Pires",
  "Nicolas Cage",
  "Keanu Reeves",
  "Cardi B",
  "Daniel Craig",
  "Freddie Mercury",
  "Marina Ruy Barbosa",
  "Narcisa Tamborindeguy",
  "Pedro Bassan",
  "Fiuk",
  "Zac Efron",
  "Sarah Andrade",
  "Rafa Kalimann",
  "Léo Santana",
  "MC Poze",
  "Esse Menino",
  "Thiago Ventura",
  "Pocoyo",
  "Mônica",
  "Lucas",
  "Vovô do Quero Café",
  "Alexander Augusto de Almeida",
  "Serjão Berranteiro",
  "Pedrão pão de batata",
  "Chico Buarque",
  "André Marques",
  "Jeremias Muito Louco",
  "Lasier Martins",
  "Ruth Lemos",
  "Flork",
  "MC Loma",
  "Inês Brasil",
  "Luva de Pedreiro",
  "João Frango",
  "João Kleber",
  "Silvio Santos",
  "Faustão",
  "Namaria",
  "Palmirinha",
  "Fábio Porchat",
  "Whindersson Nunes",
  "Felipe Neto",
  "Kéfera Buchmann",
  "Christian Figueiredo",
  "Gabi Prado",
  "Carlinhos Maia",
  "Tiririca",
  "Didi Mocó",
  "Mussum",
  "Zacarias",
  "Dedé Santana",
  "Paulo Gustavo",
  "Tatá Werneck",
  "Rodrigo Faro",
  "Celso Portiolli",
  "Eliana",
  "Xuxa",
  "Angélica",
  "Gugu Liberato",
  "Raul Gil",
  "Ratinho",
  "Datena",
  "Sonia Abrão",
  "Regina Casé",
  "Fernanda Souza",
  "Maísa Silva",
  "Larissa Manoela",
  "Maisa",
  "Camila Loures",
  "Gessica Kayane",
  "Juliette Freire",
  "Gil do Vigor",
  "Karol Conká",
  "Lucas Penteado",
  "Manu Gavassi",
  "Babu Santana",
  "Felipe Prior",
  "Pyong Lee",
  "Bianca Andrade",
  "Mari Gonzalez",
  "Victor Hugo",
  "Gizelly Bicalho",
  "Ivy Moraes",
  "Daniel Lenhardt",
  "Flayslane",
  "Marcela McGowan",
  "Thelma Assis",
  "Gabi Martins",
  "Petrix Barbosa",
  "Hadson Nery",
  "Lucas Chumbo",
  "Mari Baianinha",
  "Felipe Titto",
  "Bruna Marquezine",
  "Neymar Jr.",
  "Anitta",
  "Pabllo Vittar",
  "Bolsonaro",
  "Véio da Havan",
  "Lula",
  "Dilma",
  "Ciro Gomes",
  "Carreta Furacão",
  "MC Bin Laden",
  "Fofão",
  "Tiozão do Pavê",
  "Galvão Bueno",
  "Dercy Gonçalves",
  "Chaves",
  "Seu Madruga",
  "Chiquinha",
  "Quico",
  "Professor Girafales",
  "Kiko do BBB",
  "Rico Melquiades",
  "Tio Paulo",
  "Tiozão do Churrasco",
  "Naruto Brasileiro",
  "Zezé di Camargo",
  "Luciano Huck",
  "Louro José",
  "Fátima Bernardes",
  "Bonner",
  "Eduardo Paes",
  "Doria",
  "Sergio Moro",
  "Tirulipa",
  "Renato Aragão",
  "Didi",
  "Dedé",
  "Carlinhos Troll",
  "Cumpadre Washington",
  "Belo",
  "Leão da Proerd",
  "Patati",
  "Patatá",
  "Falcão",
  "Netinho de Paula",
  "Datena Pistola",
  "Edir Macedo",
  "RR Soares",
  "Valdemiro Santiago",
  "Padre Marcelo Rossi",
  "Pastor Cláudio Duarte",
  "Sandy",
  "Junior",
  "Serginho Groisman",
  "Cazalbé",
  "Milton Neves",
  "Caetano Veloso",
  "Clodovil",
  "Leão Lobo",
  "Nelson Ned",
  "Netinho",
  "Lacraia",
  "Mr. Catra",
  "MC Créu",
  "MC Kevinho",
  "MC Gui",
  "MC Melody",
  "MC Mirella",
  "MC Pocahontas",
  "Vera Verão",
  "Leandro Hassum",
  "Danilo Gentili",
  "Rafinha Bastos",
  "CQC",
  "Carioca",
];
